config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'users/delete'
  # Home 静的ページ
  root 'home#home'
  get 'privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  # コンタクトページ
  get 'contact/index', to: 'contact#index', as: 'contact_index'
  post 'contact/confirm', to: 'contact#confirm', as: 'contact_confirm'
  post 'contact/done', to: 'contact#done', as: 'contact_done'
  #
  # Devise
  devise_for :users, :controllers => {
      :sessions      => "users/sessions",
      :registrations => "users/registrations",
      :passwords     => "users/passwords",
      :confirmations => "users/confirmations",
      :omniauth_callbacks => "users/omniauth_callbacks"
  }
  devise_scope :user do
    patch "users/confirmation", to: "users/confirmations#confirm"
    # get "users/sign_up", to: "users/registrations#new"
  end
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/contact.rb
class Contact include ActiveModel::Model

attr_accessor :name, :email, :content

validates :name, presence: true, length: { maximum: 30 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 40 },
          format: { with: VALID_EMAIL_REGEX }
validates :content, presence: true, length: { maximum: 200 }
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def done
    @contact = Contact.new(contact_params)
    if params[:back]
      render :action => 'index'
    else
      ContactMailer.received_email(@contact).deliver_now
      render :action => 'done'
    end
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/confirm.html.erb
<div class="contact form confirm">
  <%= simple_form_for(@contact, :url => contact_done_path ) do |f| %>
    <h3>メッセージ確認</h3>
    <p><strong>名前</strong></p>
    <%= f.hidden_field :name %>
    <p class="contact_confirm_contents"><%= @contact.name %></p>
    <p><strong>メールアドレス</strong></p>
    <%= f.hidden_field :email %>
    <p class="contact_confirm_contents"><%= @contact.email %></p>
    <p><strong>内容</strong></p>
    <%= f.hidden_field :content %>
    <p class="contact_confirm_contents"><%= @contact.content %></p>
    <div class="contact_confirm_buttons">
      <%= f.button :submit, "戻る", name: 'back', :class => "contact submit return" %>
      <%= f.button :submit, "送信", :class => "contact submit confirm", method: :post  %>
    </div>
  <% end %>
</div>

app/views/contact/done.html.erb
<div class="contact form done">
  <h3>メッセージ送信完了</h3>
  <p>
    メッセージをいただきありがとうございました。<br>
    運営スタッフよりご連絡させていただきます。
  </p>
</div>

app/views/contact/index.html.erb
<div class="contact form index">
  <%= simple_form_for(@contact, url: { action: :confirm }) do |f| %>
    <h3>お問合わせ・ご要望</h3>
    <%= f.input :name, label: "名前" %>
    <%= f.input :email, label: "メールアドレス" %>
    <%= f.input :content, as: :text, input_html: { rows: 6 }, label: "お問い合せ内容（200字以内）" %>
    <%= f.button :submit, "確認画面へ", :class => "contact submit", method: :post  %>
  <% end %>
</div>