config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  get 'users/update'
  get 'users/delete'
  # Home 静的ページ
  root 'home#home'
  get 'privacy_policy', to: 'home#privacy_policy', as: 'privacy_policy'
  # コンタクトページ
  get 'contact/index', to: 'contact#index', as: 'contact_index'
  post 'contact/confirm', to: 'contact#confirm', as: 'contact_confirm'
  post 'contact/done', to: 'contact#done', as: 'contact_done'
  #
  # Devise
  devise_for :users, :controllers => {
      :sessions      => "users/sessions",
      :registrations => "users/registrations",
      :passwords     => "users/passwords",
      :confirmations => "users/confirmations",
      :omniauth_callbacks => "users/omniauth_callbacks"
  }
  devise_scope :user do
    patch "users/confirmation", to: "users/confirmations#confirm"
    # get "users/sign_up", to: "users/registrations#new"
  end
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-wrapper">
    <div id="footer-items">
      <div class="footer-item">
        <li><%= link_to "ペアリング投稿", "#" %></li>
        <li><%= link_to "お酒を登録", "#" %></li>
        <li><%= link_to "料理を登録", "#" %></li>
        <li><%= link_to "お酒から探す", "#" %></li>
        <li><%= link_to "食事から探す", "#" %></li>
<!--        <li><%#= link_to "ログアウト", destroy_user_session_path(current_user) %></li>-->
      </div>
      <div class="footer-item">
        <li><%= link_to "SAKIIKAについて", '#' %></li>
        <li><%= link_to "ペアリングの基本", '#' %></li>
        <li><%= link_to "ペアリングブログ", '#' %></li>
        <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
      </div>
      <div class="footer-item">
        <li><%= link_to "プライバシーポリシー", privacy_policy_path %></li>
        <li><%= link_to "運営情報", "#" %></li>
        <li><%= link_to "エンジニア募集", "#" %></li>
        <li><%= link_to "お問い合わせ", contact_index_path %></li>
      </div>
    </div>
    <div class="copyright">
      <p>© DonoSake ALL RIGHTS RESERVED.</p>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>DonoSake</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta name="theme-color" content="#ff7782">
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"/>
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= favicon_link_tag('favicon_3rings.ico') %>
</head>

app/views/layouts/_header.html.erb
<header>
  <div class="header-menus">

    <div class="first">
      <div class="logo">
        <%= link_to root_path do %>
          <%= image_tag "logo_donosake2.png" %>
        <% end %>
      </div>
      <div class="user-page-btn">
        <% if user_signed_in? %>
          <%= link_to user_path(current_user) do %>
            <label><i class="far fa-user"></i>マイページ</label>
          <% end %>
        <% else %>
          <%= link_to "登録・ログイン", new_user_session_path, :class => "login_top_sp" %>
        <% end %>
      </div>
    </div>
    <div class="second">
      <ul>
        <li><%= link_to "お酒を探す", "#", :class => "header menu" %></li>
        <li><%= link_to "料理を探す", "#", :class => "header menu" %></li>
        <li><%= link_to "投稿する", "#", :class => "header menu" %></li>
      </ul>
    </div>

  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/head' %>
<body>
<div id="wrapper">
  <div class="header">
    <%= render 'layouts/header' %>
  </div>
  <% if notice %>
    <div class="notice"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert"><%= alert %></div>
  <% end %>
  <div class="main-content">
    <%= yield %>
  </div>
  <div class="footer">
    <%= render 'layouts/footer' %>
  </div>
</div>
</body>
</html>